const assert = require('node:assert/strict');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const fulfillVideo = (route, base64) => {
  const body = Buffer.from(base64, 'base64');
  const range = /bytes=(\d+)-(\d*)/.exec(route.request().headers().range || '');
  if (!range) return route.fulfill({ status: 200, contentType: 'video/webm', headers: { 'accept-ranges': 'bytes' }, body });
  const start = Math.min(Number(range[1]), body.length - 1);
  const end = range[2] ? Math.min(Number(range[2]), body.length - 1) : body.length - 1;
  return route.fulfill({ status: 206, contentType: 'video/webm', headers: { 'accept-ranges': 'bytes', 'content-range': `bytes ${start}-${end}/${body.length}` }, body: body.subarray(start, end + 1) });
};

const root = path.join(__dirname, '..');
const server = http.createServer((request, response) => {
  const pathname = new URL(request.url, 'http://localhost').pathname;
  const file = path.join(root, pathname === '/' ? 'index.html' : pathname);
  response.setHeader('Content-Type', ({ '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png' })[path.extname(file)] || 'text/plain');
  fs.readFile(file, (error, data) => { if (error) { response.statusCode = 404; response.end(); } else response.end(data); });
});

(async () => {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.route('https://www.gstatic.com/firebasejs/**', route => route.abort());
    const url = `http://127.0.0.1:${server.address().port}`;
    const unlock = async () => { await page.waitForTimeout(300); await page.evaluate(() => { document.body.classList.remove('auth-locked'); document.querySelector('#authGate').hidden = true; }); };
    const enterReview = async () => { await page.locator('#reviewsNav').click(); await page.locator('#reviewsHomeGrid .reviews-home-card-open').filter({ hasText: 'Campaña test' }).click(); await page.locator('#reviewsHomeGrid .reviews-home-card-open').filter({ hasText: 'Montaje · V1' }).click(); await page.locator('#reviewsView').waitFor({ state: 'visible' }); };
    await page.goto(url);
    await unlock();
    await page.locator('#reviewsNav').click();
    assert.equal(await page.locator('#reviewsHome').isVisible(), true, 'Reviews opens on its project dashboard');
    if (process.env.REVIEW_HOME_SCREENSHOT) await page.screenshot({ path: process.env.REVIEW_HOME_SCREENSHOT, fullPage: true });
    await page.locator('#reviewsCreateProject').click();
    if (process.env.REVIEW_FORM_SCREENSHOT) await page.screenshot({ path: process.env.REVIEW_FORM_SCREENSHOT, fullPage: true });
    await page.locator('#reviewsEntityTitle').fill('Campaña test');
    await page.locator('#reviewsEntityClient').fill('Cliente test');
    await page.locator('#reviewsEntityForm button[type=submit]').click();
    if (process.env.REVIEW_VERSION_SCREENSHOT) await page.screenshot({ path: process.env.REVIEW_VERSION_SCREENSHOT, fullPage: true });
    await page.locator('#reviewsHomeGrid .reviews-home-card-open').first().click();
    assert.equal(await page.locator('#reviewsView').isVisible(), true);
    const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="360" height="640"><rect width="360" height="640" fill="#40566b"/></svg>';
    assert.equal(await page.locator('#reviewsFileInput').count(), 0, 'there is no local upload control');
    await page.evaluate(() => { const files = new DataTransfer(); files.items.add(new File(['local'], 'local.mp4', { type: 'video/mp4' })); document.querySelector('#reviewsStage').dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer: files })); });
    assert.equal(await page.locator('#reviewsCount').textContent(), '0', 'dropping a local file does not add it');
    assert.match(await page.locator('#reviewsCommentContext').textContent(), /solo podés vincular archivos/);
    await page.route('https://www.dropbox.com/scl/fi/**', route => route.fulfill({ status: 200, contentType: 'image/svg+xml', body: svg }));
    await page.locator('#reviewsLinkBtn').click();
    await page.locator('#reviewsLinkUrl').fill('https://www.dropbox.com/scl/fi/original/plano-inicial.jpg?rlkey=original');
    await page.locator('#reviewsLinkForm button[type=submit]').click();
    await page.locator('#reviewsImage').waitFor({ state: 'visible' });
    await page.waitForFunction(() => document.querySelector('#reviewsImage').naturalWidth === 360);
    const mediaBox = await page.locator('#reviewsMediaSurface').boundingBox();
    const stageBox = await page.locator('#reviewsStage').boundingBox();
    assert.ok(mediaBox.width <= stageBox.width && mediaBox.height <= stageBox.height, 'portrait media fits inside the review stage');
    await page.locator('#reviewsDrawBtn').click();
    const box = await page.locator('#reviewsCanvas').boundingBox();
    await page.mouse.move(box.x + box.width * .2, box.y + box.height * .2);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width * .7, box.y + box.height * .6, { steps: 8 });
    await page.mouse.up();
    await page.locator('#reviewsCommentText').fill('Ajustar el encuadre');
    await page.locator('#reviewsCommentForm button[type=submit]').click();
    await page.waitForFunction(() => document.querySelector('#reviewsCommentCount').textContent === '1');
    const stored = await page.evaluate(async () => new Promise((resolve, reject) => {
      const request = indexedDB.open('gb-studio-reviews-v1');
      request.onsuccess = () => { const tx = request.result.transaction('items'); const get = tx.objectStore('items').getAll(); get.onsuccess = () => resolve(get.result); get.onerror = () => reject(get.error); };
      request.onerror = () => reject(request.error);
    }));
    assert.equal(stored[0].comments[0].text, 'Ajustar el encuadre');
    assert.ok(stored[0].comments[0].strokes[0].points.length > 1, 'the drawing is attached to the comment');
    await page.locator('#reviewsBackVersions').click();
    await page.locator('#reviewsCreateVersion').click();
    await page.locator('#reviewsEntityTitle').fill('VFX · V1');
    await page.locator('#reviewsEntityCategory').selectOption('VFX');
    await page.locator('#reviewsEntityForm button[type=submit]').click();
    await page.locator('#reviewsHomeGrid .reviews-home-card-open').filter({ hasText: 'VFX · V1' }).click();
    assert.equal(await page.locator('#reviewsCount').textContent(), '0', 'a new review starts with its own empty file list');
    await page.locator('#reviewsLinkBtn').click();
    await page.locator('#reviewsLinkUrl').fill('https://www.dropbox.com/scl/fi/vfx/vfx.jpg?rlkey=vfx');
    await page.locator('#reviewsLinkForm button[type=submit]').click();
    await page.locator('#reviewsImage').waitFor({ state: 'visible' });
    await page.locator('#reviewsCommentText').fill('Corrección exclusiva de VFX');
    await page.locator('#reviewsCommentForm button[type=submit]').click();
    await page.waitForFunction(() => document.querySelector('#reviewsCommentCount').textContent === '1');
    await page.locator('#reviewsBackVersions').click();
    await page.locator('#reviewsHomeGrid .reviews-home-card-open').filter({ hasText: 'Montaje · V1' }).click();
    assert.equal(await page.locator('#reviewsCount').textContent(), '1', 'original review keeps its files and comments');
    assert.equal(await page.locator('#reviewsCommentCount').textContent(), '1', 'VFX feedback does not appear in the montage review');
    await page.locator('#reviewsRemoveMedia').click();
    assert.equal(await page.locator('#reviewsConfirmModal').isVisible(), true, 'file removal uses a designed confirmation');
    if (process.env.REVIEW_MODAL_SCREENSHOT) await page.screenshot({ path: process.env.REVIEW_MODAL_SCREENSHOT, fullPage: true });
    await page.locator('#reviewsConfirmCancel').click();
    assert.equal(await page.locator('#reviewsCount').textContent(), '1', 'cancelling preserves the file');
    await page.reload(); await unlock(); await enterReview();
    await page.waitForFunction(() => document.querySelector('#reviewsCommentCount').textContent === '1');
    assert.match(await page.locator('.reviews-comment-text').textContent(), /Ajustar el encuadre/);
    await page.locator('.reviews-comment-open').click();
    assert.equal(await page.locator('.reviews-comment.is-selected').count(), 1);
    assert.equal(await page.evaluate(() => {
      const canvas = document.querySelector('#reviewsCanvas');
      const pixels = canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height).data;
      return pixels.some((channel, index) => index % 4 === 3 && channel > 0);
    }), true, 'stored drawing is visible when its comment is selected');
    await page.locator('.reviews-comment-actions button').first().click();
    await page.locator('.reviews-comment.is-resolved').waitFor();
    assert.equal(await page.locator('.reviews-comment.is-resolved').count(), 1);
    await page.locator('#storyboardsNav').click();
    assert.equal(await page.locator('#dashboardView').isVisible(), true);
    await enterReview();
    assert.equal(await page.locator('#reviewsCommentCount').textContent(), '1');
    await page.locator('#reviewsLinkBtn').click();
    await page.locator('#reviewsLinkUrl').fill('https://notdropbox.com/scl/fi/id/plano.jpg');
    await page.locator('#reviewsLinkForm button[type=submit]').click();
    assert.match(await page.locator('#reviewsLinkMessage').textContent(), /dropbox.com/);
    assert.equal(await page.locator('#reviewsCount').textContent(), '1', 'invalid domains cannot be linked');
    await page.locator('#reviewsLinkUrl').fill('https://www.dropbox.com/scl/fo/folderid?rlkey=abc123');
    await page.locator('#reviewsLinkForm button[type=submit]').click();
    assert.equal(await page.locator('#reviewsCount').textContent(), '1', 'folder links cannot be linked as media');
    await page.locator('#reviewsLinkUrl').fill('https://www.dropbox.com/scl/fi/id/plano.jpg?rlkey=abc123&dl=0');
    assert.equal(await page.locator('#reviewsLinkKind').inputValue(), 'image');
    await page.locator('#reviewsLinkForm button[type=submit]').click();
    await page.waitForFunction(() => document.querySelector('#reviewsCount').textContent === '2');
    await page.waitForFunction(() => document.querySelector('#reviewsImage').naturalWidth === 360);
    assert.match(await page.locator('#reviewsImage').getAttribute('src'), /rlkey=abc123&raw=1/);
    assert.equal(await page.locator('#reviewsOpenSource').isVisible(), true);
    assert.match(await page.locator('#reviewsOpenSource').getAttribute('href'), /rlkey=abc123$/);
    assert.equal(await page.locator('#reviewsMediaError').isVisible(), false);
    await page.locator('#reviewsLinkBtn').click();
    await page.locator('#reviewsLinkUrl').fill('https://www.dropbox.com/scl/fi/id/plano.jpg?rlkey=abc123&raw=1');
    await page.locator('#reviewsLinkForm button[type=submit]').click();
    assert.equal(await page.locator('#reviewsCount').textContent(), '2', 'the same Dropbox file is not linked twice');
    await page.locator('#reviewsLinkCancel').click();
    await page.locator('#reviewsCommentText').fill('Corrección sobre Dropbox');
    await page.locator('#reviewsCommentForm button[type=submit]').click();
    await page.waitForFunction(() => document.querySelector('#reviewsCommentCount').textContent === '1');
    await page.reload(); await unlock(); await enterReview();
    await page.waitForFunction(() => document.querySelector('#reviewsImage').naturalWidth === 360);
    assert.match(await page.locator('.reviews-comment-text').first().textContent(), /Corrección sobre Dropbox/);
    const dropboxStorage = await page.evaluate(async () => new Promise((resolve, reject) => {
      const request = indexedDB.open('gb-studio-reviews-v1');
      request.onsuccess = () => { const tx = request.result.transaction(['items', 'media']); const item = tx.objectStore('items').getAll(); const media = tx.objectStore('media').getAll(); tx.oncomplete = () => resolve({ item: item.result.find(record => record.name === 'plano.jpg'), mediaCount: media.result.length }); tx.onerror = () => reject(tx.error); };
      request.onerror = () => reject(request.error);
    }));
    assert.equal(dropboxStorage.item.comments[0].text, 'Corrección sobre Dropbox');
    assert.equal(dropboxStorage.mediaCount, 0, 'Dropbox assets are never copied to IndexedDB');
    const videoFixture = await page.evaluate(async () => {
      if (!window.MediaRecorder || !MediaRecorder.isTypeSupported('video/webm;codecs=vp8')) return null;
      const source = document.createElement('canvas'); source.width = 320; source.height = 180;
      const graphics = source.getContext('2d'); graphics.fillStyle = '#547d8e'; graphics.fillRect(0, 0, 320, 180);
      const stream = source.captureStream(10);
      const recorder = new MediaRecorder(stream, { mimeType: 'video/webm;codecs=vp8' });
      const chunks = []; recorder.ondataavailable = event => { if (event.data.size) chunks.push(event.data); };
      const done = new Promise(resolve => { recorder.onstop = resolve; });
      let frame = 0;
      const animation = setInterval(() => { graphics.fillStyle = frame++ % 2 ? '#547d8e' : '#647d8e'; graphics.fillRect(0, 0, 320, 180); }, 50);
      recorder.start(); await new Promise(resolve => setTimeout(resolve, 1100)); clearInterval(animation); recorder.stop(); await done;
      stream.getTracks().forEach(track => track.stop());
      const file = new File(chunks, 'revision.webm', { type: 'video/webm' });
      return new Promise(resolve => { const reader = new FileReader(); reader.onload = () => resolve(reader.result.split(',')[1]); reader.readAsDataURL(file); });
    });
    assert.ok(videoFixture, 'the test browser can generate a video fixture');
    await page.route('https://www.dropbox.com/scl/fi/**', route => route.request().url().includes('.webm')
      ? fulfillVideo(route, videoFixture)
      : route.fulfill({ status: 200, contentType: 'image/svg+xml', body: svg }));
    await page.locator('#reviewsLinkBtn').click();
    await page.locator('#reviewsLinkUrl').fill('https://www.dropbox.com/scl/fi/video-local/revision-base.webm?rlkey=local');
    await page.locator('#reviewsLinkForm button[type=submit]').click();
    await page.locator('#reviewsVideo').waitFor({ state: 'visible' });
    await page.waitForFunction(() => document.querySelector('#reviewsVideo').readyState >= 1);
    await page.locator('#reviewsCommentText').fill('Revisar el corte');
    await page.locator('#reviewsCommentForm button[type=submit]').click();
    await page.waitForFunction(() => document.querySelector('#reviewsCommentCount').textContent === '1');
    assert.equal(await page.locator('.reviews-marker').count(), 1);
    await page.locator('.reviews-marker').click();
    assert.equal(await page.locator('.reviews-comment.is-selected').count(), 1);
    assert.ok(await page.evaluate(() => document.querySelector('#reviewsVideo').duration) > .5, 'video fixture contains playable frames');
    await page.locator('#reviewsPlayBtn').click();
    await page.waitForFunction(() => document.querySelector('#reviewsVideo').currentTime > .05);
    await page.locator('#storyboardsNav').click();
    assert.equal(await page.evaluate(() => document.querySelector('#reviewsVideo').paused), true, 'video pauses when leaving Reviews');
    await enterReview();
    await page.locator('#reviewsDrawBtn').click();
    const videoBox = await page.locator('#reviewsCanvas').boundingBox();
    await page.mouse.move(videoBox.x + videoBox.width * .3, videoBox.y + videoBox.height * .3);
    await page.mouse.down();
    await page.mouse.move(videoBox.x + videoBox.width * .6, videoBox.y + videoBox.height * .5, { steps: 5 });
    await page.mouse.up();
    await page.locator('#reviewsCommentText').fill('Marcar el cuadro');
    await page.locator('#reviewsCommentForm button[type=submit]').click();
    await page.waitForFunction(() => document.querySelector('#reviewsCommentCount').textContent === '2');
    assert.equal(await page.locator('.reviews-marker').count(), 2);
    assert.equal(await page.evaluate(async () => new Promise(resolve => {
      const request = indexedDB.open('gb-studio-reviews-v1');
      request.onsuccess = () => { const tx = request.result.transaction('items'); const get = tx.objectStore('items').getAll(); get.onsuccess = () => resolve(get.result.find(item => item.kind === 'video').comments.some(comment => comment.strokes.length)); };
    })), true, 'video annotation is saved with its comment');
    await page.locator('#reviewsFrameStart').fill('1001');
    await page.locator('#reviewsFrameStart').dispatchEvent('change');
    await page.evaluate(() => { document.querySelector('#reviewsVideo').currentTime = 0; });
    await page.waitForFunction(() => document.querySelector('#reviewsFrameNumber').textContent.includes('1001'));
    assert.match(await page.locator('#reviewsFrameNumber').textContent(), /1001/);
    await page.locator('#reviewsTimelineMode').selectOption('frames');
    await page.locator('#reviewsFrameJump').fill('1005');
    await page.locator('#reviewsFrameJump').dispatchEvent('change');
    await page.waitForFunction(() => document.querySelector('#reviewsFrameNumber').textContent.includes('1005'));
    assert.ok(Math.abs(await page.evaluate(() => document.querySelector('#reviewsVideo').currentTime) - 4 / 24) < .02, 'frame number seeks to an FPS-aligned video position');
    await page.locator('#reviewsNextFrame').click();
    assert.match(await page.locator('#reviewsFrameNumber').textContent(), /1006/, 'one-frame button advances one frame');
    const frameSeekBox = await page.locator('#reviewsSeek').boundingBox();
    await page.mouse.move(frameSeekBox.x + frameSeekBox.width / 2, frameSeekBox.y + frameSeekBox.height / 2);
    await page.mouse.down(); await page.mouse.move(frameSeekBox.x + frameSeekBox.width / 2 + 16, frameSeekBox.y + frameSeekBox.height / 2, { steps: 4 }); await page.mouse.up();
    assert.match(await page.locator('#reviewsFrameNumber').textContent(), /1008/, 'precision drag advances one frame for each 8 px');
    assert.equal(await page.locator('#reviewsSeek').getAttribute('step'), '1');
    await page.reload(); await unlock(); await enterReview();
    await page.waitForFunction(() => document.querySelector('#reviewsVideo').duration > .5);
    assert.equal(await page.locator('#reviewsTimelineMode').inputValue(), 'frames', 'frame mode persists for this video');
    assert.equal(await page.locator('#reviewsFrameStart').inputValue(), '1001');
    await page.locator('#reviewsTimelineMode').selectOption('time');
    await page.evaluate(() => { document.activeElement.blur(); document.querySelector('#reviewsVideo').currentTime = .2; });
    await page.keyboard.press('I');
    assert.notEqual(await page.locator('#reviewsInValue').textContent(), '—');
    await page.evaluate(() => { document.querySelector('#reviewsVideo').currentTime = .8; });
    await page.keyboard.press('O');
    assert.notEqual(await page.locator('#reviewsOutValue').textContent(), '—');
    await page.keyboard.press('ArrowLeft');
    const steppedTime = await page.evaluate(() => document.querySelector('#reviewsVideo').currentTime);
    assert.ok(steppedTime < .8 && steppedTime > .6, 'left arrow steps back one estimated frame');
    await page.keyboard.press('Home');
    assert.ok(await page.evaluate(() => document.querySelector('#reviewsVideo').currentTime) < .05);
    await page.keyboard.press('End');
    assert.ok(await page.evaluate(() => document.querySelector('#reviewsVideo').currentTime) > .9);
    await page.keyboard.press('ArrowUp');
    assert.ok(await page.evaluate(() => document.querySelector('#reviewsVideo').currentTime) < .9, 'up arrow jumps to a note');
    await page.locator('#reviewsStage').hover();
    await page.mouse.wheel(0, -300);
    assert.notEqual(await page.locator('#reviewsZoomValue').textContent(), '100%', 'wheel zooms');
    await page.keyboard.press('H');
    assert.equal(await page.locator('#reviewsZoomValue').textContent(), '100%', 'H fits the media');
    const zoomBox = await page.locator('#reviewsMediaSurface').boundingBox();
    await page.keyboard.down('z');
    await page.mouse.click(zoomBox.x + zoomBox.width / 2, zoomBox.y + zoomBox.height / 2);
    await page.keyboard.up('z');
    assert.notEqual(await page.locator('#reviewsZoomValue').textContent(), '100%', 'Z + pointer click zooms for tablet input');
    await page.keyboard.press('H');
    await page.keyboard.press('Q');
    assert.equal(await page.evaluate(() => document.body.classList.contains('reviews-hud-hidden')), true);
    await page.keyboard.press('Q');
    assert.equal(await page.evaluate(() => document.body.classList.contains('reviews-hud-hidden')), false);
    await page.keyboard.press('F');
    await page.waitForFunction(() => document.fullscreenElement?.id === 'reviewsView');
    await page.keyboard.press('F');
    await page.waitForFunction(() => !document.fullscreenElement);
    await page.locator('#reviewsScreenshotBtn').click();
    await page.waitForFunction(() => document.querySelector('#reviewsCommentContext').textContent.includes('Dropbox no habilita'), null, { timeout: 3000 });
    await page.locator('#reviewsSketchBtn').click();
    const scratchBox = await page.locator('#reviewsCanvas').boundingBox();
    await page.mouse.move(scratchBox.x + 30, scratchBox.y + 30); await page.mouse.down(); await page.mouse.move(scratchBox.x + 100, scratchBox.y + 80, { steps: 4 }); await page.mouse.up();
    assert.equal(await page.locator('#reviewsSketchBtn').getAttribute('aria-pressed'), 'true');
    await page.locator('#reviewsCommentText').fill('Solo texto, dibujo temporal');
    await page.locator('#reviewsCommentForm button[type=submit]').click();
    await page.waitForFunction(() => document.querySelector('#reviewsCommentCount').textContent === '3');
    assert.equal(await page.evaluate(async () => new Promise(resolve => { const open = indexedDB.open('gb-studio-reviews-v1'); open.onsuccess = () => { const request = open.result.transaction('items').objectStore('items').getAll(); request.onsuccess = () => resolve(request.result.find(item => item.kind === 'video').comments.at(-1).strokes.length); }; })), 0, 'temporary drawing is not saved with a comment');
    await page.route('https://www.dropbox.com/scl/fi/**', route => route.request().url().includes('revision.webm')
      ? fulfillVideo(route, videoFixture)
      : route.fulfill({ status: 200, contentType: 'image/svg+xml', body: svg }));
    await page.locator('#reviewsLinkBtn').click();
    await page.locator('#reviewsLinkUrl').fill('https://www.dropbox.com/scl/fi/videoid/revision.webm?rlkey=xyz&dl=0');
    assert.equal(await page.locator('#reviewsLinkKind').inputValue(), 'video');
    await page.locator('#reviewsLinkForm button[type=submit]').click();
    await page.waitForFunction(() => document.querySelector('#reviewsVideo').getAttribute('src')?.includes('/videoid/'));
    await page.waitForFunction(() => document.querySelector('#reviewsVideo').duration > .5);
    assert.match(await page.locator('#reviewsVideo').getAttribute('src'), /rlkey=xyz&raw=1/);
    await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
    await page.locator('#reviewsShareBtn').click();
    const copiedLink = await page.evaluate(() => navigator.clipboard.readText());
    assert.match(copiedLink, /#review=/);
    assert.equal(new URLSearchParams(new URL(copiedLink).hash.slice(1)).get('review'), 'https://www.dropbox.com/scl/fi/videoid/revision.webm?rlkey=xyz');
    await page.locator('#reviewsCommentText').fill('Cambio en video de Dropbox');
    await page.locator('#reviewsCommentForm button[type=submit]').click();
    await page.waitForFunction(() => document.querySelector('#reviewsCommentCount').textContent === '1');
    assert.equal(await page.locator('.reviews-marker').count(), 1, 'Dropbox video has timed comments');
    await page.locator('#reviewsAddSection').click();
    await page.locator('#reviewsSectionName').fill('Última versión');
    await page.locator('#reviewsSectionForm button[type=submit]').click();
    await page.locator('.reviews-section').filter({ hasText: 'Última versión' }).waitFor();
    await page.locator('.reviews-file.is-active').dragTo(page.locator('.reviews-section').filter({ hasText: 'Última versión' }).locator('.reviews-section-files'));
    await page.waitForFunction(() => [...document.querySelectorAll('.reviews-section')].some(section => section.querySelector('strong')?.textContent === 'Última versión' && section.querySelector('.reviews-file.is-active')));
    const latestSection = page.locator('.reviews-section').filter({ hasText: 'Última versión' });
    await page.locator('.reviews-file').filter({ hasText: 'revision-base.webm' }).dragTo(latestSection.locator('.reviews-section-files'));
    await page.waitForFunction(() => [...document.querySelectorAll('.reviews-section')].some(section => section.querySelector('strong')?.textContent === 'Última versión' && section.querySelectorAll('.reviews-file').length === 2));
    await latestSection.locator('.reviews-file').filter({ hasText: 'revision-base.webm' }).dragTo(latestSection.locator('.reviews-file').filter({ hasText: 'revision.webm' }));
    await page.waitForFunction(() => [...document.querySelectorAll('.reviews-section')].find(section => section.querySelector('strong')?.textContent === 'Última versión')?.querySelector('.reviews-file')?.textContent.includes('revision-base.webm'));
    if (process.env.REVIEW_SECTIONS_SCREENSHOT) await page.screenshot({ path: process.env.REVIEW_SECTIONS_SCREENSHOT, fullPage: true });
    await page.reload(); await unlock(); await enterReview();
    assert.equal(await page.locator('.reviews-section').filter({ hasText: 'Última versión' }).locator('.reviews-file').count(), 2, 'section assignment survives reload');
    assert.match(await page.locator('.reviews-section').filter({ hasText: 'Última versión' }).locator('.reviews-file').first().textContent(), /revision-base.webm/, 'custom file order survives reload');
    await page.locator('button[aria-label="Renombrar sección Última versión"]').click();
    await page.locator('#reviewsSectionName').fill('Corte final');
    await page.locator('#reviewsSectionForm button[type=submit]').click();
    await page.locator('.reviews-section').filter({ hasText: 'Corte final' }).waitFor();
    await page.locator('button[aria-label="Eliminar sección Corte final"]').click();
    await page.locator('#reviewsConfirmAccept').click();
    await page.waitForFunction(() => ![...document.querySelectorAll('.reviews-section-heading strong')].some(item => item.textContent === 'Corte final'));
    assert.equal(await page.locator('.reviews-section').filter({ hasText: 'Sin clasificar' }).locator('.reviews-file.is-active').count(), 1, 'deleting a section moves its file without deleting it');
    if (process.env.REVIEW_TEST_FBX) {
      const fixture = await page.request.get('https://raw.githubusercontent.com/mrdoob/three.js/r186/examples/models/fbx/stanford-bunny.fbx');
      assert.equal(fixture.ok(), true, 'official FBX example is available');
      const fbxBody = await fixture.body();
      await page.route('https://www.dropbox.com/scl/fi/fbx/**', route => route.fulfill({ status: 200, contentType: 'application/octet-stream', headers: { 'access-control-allow-origin': '*' }, body: fbxBody }));
      await page.locator('#reviewsLinkBtn').click();
      await page.locator('#reviewsLinkUrl').fill('https://www.dropbox.com/scl/fi/fbx/stanford-bunny.fbx?rlkey=fbx');
      assert.equal(await page.locator('#reviewsLinkKind').inputValue(), 'model');
      await page.locator('#reviewsLinkForm button[type=submit]').click();
      await page.locator('#reviewsModel canvas').waitFor({ state: 'visible', timeout: 30000 });
      assert.equal(await page.locator('#reviewsMediaError').isVisible(), false, 'FBX model renders without an error');
    }
    if (process.env.REVIEW_SCREENSHOT) await page.screenshot({ path: process.env.REVIEW_SCREENSHOT, fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.locator('#reviewsNav').isVisible(), true);
    assert.equal(await page.locator('#reviewsCommentForm').isVisible(), true);
    await page.locator('#reviewsLinkBtn').click();
    assert.equal(await page.locator('#reviewsLinkForm').isVisible(), true);
    assert.equal(await page.evaluate(() => document.querySelector('#reviewsLinkForm').getBoundingClientRect().bottom <= document.querySelector('.reviews-library').getBoundingClientRect().bottom + 1), true, 'Dropbox link form fits inside its library panel');
    if (process.env.REVIEW_MOBILE_SCREENSHOT) await page.screenshot({ path: process.env.REVIEW_MOBILE_SCREENSHOT, fullPage: true });
    const mobileOverflow = await page.evaluate(() => ({ width: document.documentElement.scrollWidth, viewport: window.innerWidth, elements: [...document.querySelectorAll('#reviewsView *')].filter(element => element.getBoundingClientRect().right > window.innerWidth + 1).slice(0, 8).map(element => ({ tag: element.tagName, id: element.id, className: String(element.className), right: element.getBoundingClientRect().right })) }));
    assert.ok(mobileOverflow.width <= mobileOverflow.viewport + 1, `mobile review layout fits viewport width: ${JSON.stringify(mobileOverflow)}`);
    assert.deepEqual(errors, [], `browser errors: ${errors.join('; ')}`);
    await page.locator('#reviewsBackVersions').click();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true, 'review versions dashboard fits a phone');
    await page.locator('.reviews-home-card-actions button[aria-label="Eliminar VFX · V1"]').click();
    assert.equal(await page.locator('#reviewsConfirmModal').isVisible(), true);
    await page.locator('#reviewsConfirmAccept').click();
    await page.waitForFunction(() => ![...document.querySelectorAll('#reviewsHomeGrid .reviews-home-card-open')].some(card => card.textContent.includes('VFX · V1')));
    assert.equal(await page.locator('#reviewsHomeGrid .reviews-home-card-open').filter({ hasText: 'VFX · V1' }).count(), 0, 'deleting one review keeps the project');
    assert.equal(await page.evaluate(async () => new Promise(resolve => { const open = indexedDB.open('gb-studio-reviews-v1'); open.onsuccess = () => { const get = open.result.transaction('items').objectStore('items').getAll(); get.onsuccess = () => resolve(get.result.some(record => record.name === 'vfx.jpg')); }; })), false, 'deleting a review removes only its files and comments');
    await page.locator('#reviewsBackProjects').click();
    await page.locator('#reviewsCreateProject').click();
    await page.locator('#reviewsEntityTitle').fill('Proyecto temporal');
    await page.locator('#reviewsEntityClient').fill('Cliente temporal');
    await page.locator('#reviewsEntityForm button[type=submit]').click();
    await page.locator('#reviewsBackProjects').click();
    await page.locator('.reviews-home-card-actions button[aria-label="Editar Proyecto temporal"]').click();
    await page.locator('#reviewsEntityTitle').fill('Proyecto temporal editado');
    await page.locator('#reviewsEntityForm button[type=submit]').click();
    await page.locator('#reviewsHomeGrid .reviews-home-card-open').filter({ hasText: 'Proyecto temporal editado' }).waitFor();
    assert.equal(await page.locator('#reviewsHomeGrid .reviews-home-card-open').filter({ hasText: 'Proyecto temporal editado' }).count(), 1, 'project title is editable on its card');
    await page.locator('.reviews-home-card-actions button[aria-label="Eliminar Proyecto temporal editado"]').click();
    await page.locator('#reviewsConfirmCancel').click();
    assert.equal(await page.locator('#reviewsHomeGrid .reviews-home-card-open').filter({ hasText: 'Proyecto temporal editado' }).count(), 1, 'cancel keeps project');
    await page.locator('.reviews-home-card-actions button[aria-label="Eliminar Proyecto temporal editado"]').click();
    await page.locator('#reviewsConfirmAccept').click();
    await page.waitForFunction(() => ![...document.querySelectorAll('#reviewsHomeGrid .reviews-home-card-open')].some(card => card.textContent.includes('Proyecto temporal editado')));
    assert.equal(await page.locator('#reviewsHomeGrid .reviews-home-card-open').filter({ hasText: 'Proyecto temporal editado' }).count(), 0, 'confirmation deletes only the selected project');
    const guest = await browser.newPage({ viewport: { width: 1280, height: 800 } });
    try {
      await guest.route('https://www.gstatic.com/firebasejs/**', route => route.abort());
      await guest.route('https://www.dropbox.com/scl/fi/**', route => route.fulfill({ status: 200, contentType: 'video/webm', body: Buffer.from(videoFixture, 'base64') }));
      const shareHash = new URLSearchParams({ review: 'https://www.dropbox.com/scl/fi/videoid/revision.webm?rlkey=xyz', kind: 'video' });
      await guest.goto(`${url}/#${shareHash}`);
      await guest.waitForFunction(() => document.querySelector('#reviewsVideo').duration > .5);
      assert.equal(await guest.locator('#reviewsView').isVisible(), true, 'a shared link opens directly on the video');
      const guestBounds = await guest.evaluate(() => ({ stage: document.querySelector('#reviewsStage').getBoundingClientRect().toJSON(), media: document.querySelector('#reviewsMediaSurface').getBoundingClientRect().toJSON() }));
      assert.ok(guestBounds.media.bottom <= guestBounds.stage.bottom - 10 && guestBounds.media.top >= guestBounds.stage.top + 10, `guest video fits stage: ${JSON.stringify(guestBounds)}`);
      assert.equal(await guest.locator('#authGate').isVisible(), false, 'the video can be viewed without login');
      assert.equal(await guest.locator('#reviewsGuestPrompt').isVisible(), true, 'login is requested only for comments');
      assert.equal(await guest.locator('#reviewsCommentForm').isVisible(), false);
      if (process.env.REVIEW_GUEST_SCREENSHOT) await guest.screenshot({ path: process.env.REVIEW_GUEST_SCREENSHOT, fullPage: true });
      await guest.setViewportSize({ width: 390, height: 844 });
      assert.equal(await guest.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true, 'guest player fits a phone');
      assert.equal(await guest.locator('#reviewsGuestPrompt').isVisible(), true);
      await guest.locator('#storyboardsNav').click();
      assert.equal(await guest.locator('#authGate').isVisible(), true, 'storyboards remain protected');
    } finally { await guest.close(); }
    const migration = await browser.newPage();
    try {
      await migration.route('**/reviews.js*', route => route.abort());
      await migration.route('https://www.gstatic.com/firebasejs/**', route => route.abort());
      await migration.goto(url);
      await migration.evaluate(async () => {
        await new Promise((resolve, reject) => { const request = indexedDB.open('gb-studio-reviews-v1', 1); request.onupgradeneeded = () => { request.result.createObjectStore('items', { keyPath: 'id' }); request.result.createObjectStore('media'); }; request.onsuccess = () => { const db = request.result; const tx = db.transaction(['items', 'media'], 'readwrite'); tx.objectStore('items').put({ id: 'legacy-file', name: 'montaje-viejo.mp4', kind: 'video', size: 100, comments: [{ id: 'comment-1', text: 'Conservar comentario', time: 0, strokes: [], createdAt: '2026-01-01' }], createdAt: '2026-01-01', updatedAt: '2026-01-01' }); tx.objectStore('media').put(new Blob(['video original'], { type: 'video/mp4' }), 'legacy-file'); tx.oncomplete = () => { db.close(); resolve(); }; tx.onerror = () => reject(tx.error); }; request.onerror = () => reject(request.error); });
      });
      await migration.unroute('**/reviews.js*');
      await migration.reload();
      await migration.waitForTimeout(300);
      await migration.evaluate(() => { document.body.classList.remove('auth-locked'); document.querySelector('#authGate').hidden = true; });
      await migration.locator('#reviewsNav').click();
      await migration.locator('#reviewsHomeGrid .reviews-home-card-open').filter({ hasText: 'Reviews anteriores' }).click();
      assert.equal(await migration.locator('#reviewsHomeGrid .reviews-home-card-open').filter({ hasText: 'Review original' }).count(), 1, 'old records are grouped in a legacy review');
      const migrated = await migration.evaluate(async () => new Promise(resolve => { const open = indexedDB.open('gb-studio-reviews-v1'); open.onsuccess = () => { const get = open.result.transaction('items').objectStore('items').get('legacy-file'); get.onsuccess = () => resolve(get.result); }; }));
      assert.ok(migrated.projectId && migrated.versionId && migrated.comments[0].text === 'Conservar comentario', 'migration preserves existing feedback');
      assert.equal(await migration.evaluate(async () => new Promise(resolve => { const open = indexedDB.open('gb-studio-reviews-v1'); open.onsuccess = () => { const get = open.result.transaction('media').objectStore('media').get('legacy-file'); get.onsuccess = () => resolve(get.result?.size || 0); }; })), 14, 'migration preserves the original local media');
    } finally { await migration.close(); }
    console.log('Reviews smoke passed: Dropbox-only linking, sections, frame scrubbing, comments, migration, and guest viewing.');
  } finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
})().catch(error => { console.error(error); process.exitCode = 1; });
