const assert = require('node:assert/strict');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');

const root = path.join(__dirname, '..');
const server = http.createServer((request, response) => {
  const pathname = new URL(request.url, 'http://localhost').pathname;
  const file = path.join(root, pathname === '/' ? 'index.html' : pathname);
  response.setHeader('Content-Type', ({ '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png' })[path.extname(file)] || 'text/plain');
  fs.readFile(file, (error, data) => { if (error) { response.statusCode = 404; response.end(); } else response.end(data); });
});

(async () => {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.route('https://www.gstatic.com/firebasejs/**', route => route.abort());
    const url = `http://127.0.0.1:${server.address().port}`;
    const unlock = async () => { await page.waitForTimeout(300); await page.evaluate(() => { document.body.classList.remove('auth-locked'); document.querySelector('#authGate').hidden = true; }); };
    await page.goto(url);
    await unlock();
    await page.locator('#reviewsNav').click();
    assert.equal(await page.locator('#reviewsView').isVisible(), true);
    const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="360" height="640"><rect width="360" height="640" fill="#40566b"/></svg>';
    await page.locator('#reviewsFileInput').setInputFiles({ name: 'plano.svg', mimeType: 'image/svg+xml', buffer: Buffer.from(svg) });
    await page.locator('#reviewsImage').waitFor({ state: 'visible' });
    await page.waitForFunction(() => document.querySelector('#reviewsImage').naturalWidth === 360);
    const mediaBox = await page.locator('#reviewsMediaSurface').boundingBox();
    const stageBox = await page.locator('#reviewsStage').boundingBox();
    assert.ok(mediaBox.width <= stageBox.width && mediaBox.height <= stageBox.height, 'portrait media fits inside the review stage');
    await page.locator('#reviewsDrawBtn').click();
    const box = await page.locator('#reviewsCanvas').boundingBox();
    await page.mouse.move(box.x + box.width * .2, box.y + box.height * .2);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width * .7, box.y + box.height * .6, { steps: 8 });
    await page.mouse.up();
    await page.locator('#reviewsCommentText').fill('Ajustar el encuadre');
    await page.locator('#reviewsCommentForm button[type=submit]').click();
    await page.waitForFunction(() => document.querySelector('#reviewsCommentCount').textContent === '1');
    const stored = await page.evaluate(async () => new Promise((resolve, reject) => {
      const request = indexedDB.open('gb-studio-reviews-v1');
      request.onsuccess = () => { const tx = request.result.transaction('items'); const get = tx.objectStore('items').getAll(); get.onsuccess = () => resolve(get.result); get.onerror = () => reject(get.error); };
      request.onerror = () => reject(request.error);
    }));
    assert.equal(stored[0].comments[0].text, 'Ajustar el encuadre');
    assert.ok(stored[0].comments[0].strokes[0].points.length > 1, 'the drawing is attached to the comment');
    await page.reload(); await unlock(); await page.locator('#reviewsNav').click();
    await page.waitForFunction(() => document.querySelector('#reviewsCommentCount').textContent === '1');
    assert.match(await page.locator('.reviews-comment-text').textContent(), /Ajustar el encuadre/);
    await page.locator('.reviews-comment-open').click();
    assert.equal(await page.locator('.reviews-comment.is-selected').count(), 1);
    assert.equal(await page.evaluate(() => {
      const canvas = document.querySelector('#reviewsCanvas');
      const pixels = canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height).data;
      return pixels.some((channel, index) => index % 4 === 3 && channel > 0);
    }), true, 'stored drawing is visible when its comment is selected');
    await page.locator('.reviews-comment-actions button').first().click();
    await page.locator('.reviews-comment.is-resolved').waitFor();
    assert.equal(await page.locator('.reviews-comment.is-resolved').count(), 1);
    await page.locator('#storyboardsNav').click();
    assert.equal(await page.locator('#dashboardView').isVisible(), true);
    await page.locator('#reviewsNav').click();
    assert.equal(await page.locator('#reviewsCommentCount').textContent(), '1');
    const videoSupported = await page.evaluate(async () => {
      if (!window.MediaRecorder || !MediaRecorder.isTypeSupported('video/webm;codecs=vp8')) return false;
      const source = document.createElement('canvas'); source.width = 320; source.height = 180;
      const graphics = source.getContext('2d'); graphics.fillStyle = '#547d8e'; graphics.fillRect(0, 0, 320, 180);
      const stream = source.captureStream(10);
      const recorder = new MediaRecorder(stream, { mimeType: 'video/webm;codecs=vp8' });
      const chunks = []; recorder.ondataavailable = event => { if (event.data.size) chunks.push(event.data); };
      const done = new Promise(resolve => { recorder.onstop = resolve; });
      let frame = 0;
      const animation = setInterval(() => { graphics.fillStyle = frame++ % 2 ? '#547d8e' : '#647d8e'; graphics.fillRect(0, 0, 320, 180); }, 50);
      recorder.start(); await new Promise(resolve => setTimeout(resolve, 1100)); clearInterval(animation); recorder.stop(); await done;
      stream.getTracks().forEach(track => track.stop());
      const input = document.querySelector('#reviewsFileInput'); const transfer = new DataTransfer();
      transfer.items.add(new File(chunks, 'revision.webm', { type: 'video/webm' }));
      input.files = transfer.files; input.dispatchEvent(new Event('change', { bubbles: true }));
      return true;
    });
    assert.equal(videoSupported, true, 'the test browser can generate a video fixture');
    await page.locator('#reviewsVideo').waitFor({ state: 'visible' });
    await page.waitForFunction(() => document.querySelector('#reviewsVideo').readyState >= 1);
    await page.locator('#reviewsCommentText').fill('Revisar el corte');
    await page.locator('#reviewsCommentForm button[type=submit]').click();
    await page.waitForFunction(() => document.querySelector('#reviewsCommentCount').textContent === '1');
    assert.equal(await page.locator('.reviews-marker').count(), 1);
    await page.locator('.reviews-marker').click();
    assert.equal(await page.locator('.reviews-comment.is-selected').count(), 1);
    assert.ok(await page.evaluate(() => document.querySelector('#reviewsVideo').duration) > .5, 'video fixture contains playable frames');
    await page.locator('#reviewsPlayBtn').click();
    await page.waitForFunction(() => document.querySelector('#reviewsVideo').currentTime > .05);
    await page.locator('#storyboardsNav').click();
    assert.equal(await page.evaluate(() => document.querySelector('#reviewsVideo').paused), true, 'video pauses when leaving Reviews');
    await page.locator('#reviewsNav').click();
    await page.locator('#reviewsDrawBtn').click();
    const videoBox = await page.locator('#reviewsCanvas').boundingBox();
    await page.mouse.move(videoBox.x + videoBox.width * .3, videoBox.y + videoBox.height * .3);
    await page.mouse.down();
    await page.mouse.move(videoBox.x + videoBox.width * .6, videoBox.y + videoBox.height * .5, { steps: 5 });
    await page.mouse.up();
    await page.locator('#reviewsCommentText').fill('Marcar el cuadro');
    await page.locator('#reviewsCommentForm button[type=submit]').click();
    await page.waitForFunction(() => document.querySelector('#reviewsCommentCount').textContent === '2');
    assert.equal(await page.locator('.reviews-marker').count(), 2);
    assert.equal(await page.evaluate(async () => new Promise(resolve => {
      const request = indexedDB.open('gb-studio-reviews-v1');
      request.onsuccess = () => { const tx = request.result.transaction('items'); const get = tx.objectStore('items').getAll(); get.onsuccess = () => resolve(get.result.find(item => item.kind === 'video').comments.some(comment => comment.strokes.length)); };
    })), true, 'video annotation is saved with its comment');
    if (process.env.REVIEW_SCREENSHOT) await page.screenshot({ path: process.env.REVIEW_SCREENSHOT, fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.locator('#reviewsNav').isVisible(), true);
    assert.equal(await page.locator('#reviewsCommentForm').isVisible(), true);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true, 'mobile review layout fits viewport width');
    if (process.env.REVIEW_MOBILE_SCREENSHOT) await page.screenshot({ path: process.env.REVIEW_MOBILE_SCREENSHOT, fullPage: true });
    assert.deepEqual(errors, [], `browser errors: ${errors.join('; ')}`);
    console.log('Reviews smoke passed: image and video upload, drawing, comments, timeline, reload, and resolve.');
  } finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
})().catch(error => { console.error(error); process.exitCode = 1; });
